# -*- coding: utf-8 -*-
"""Home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAbSY9P-1E_ppC6L1h9KynzYzfEAGokm
"""

import streamlit as st

st.set_page_config(
    page_title="Dashboard Prediksi Kopi",
    page_icon="☕",
    layout="centered"
)

st.title("☕ Dashboard Prediksi Penjualan Kopi")
st.write("""
Selamat datang di aplikasi **Prediksi Penjualan Kopi**.

Gunakan menu di sebelah kiri (sidebar) untuk:
- 🔮 **Prediksi Kopi** – melakukan prediksi penjualan berdasarkan jenis kopi, umur, jam, dll.
- (Nanti bisa ditambah halaman lain, misalnya **Analisis Data**, **Tentang Model**, dll.)
""")

st.markdown("---")
st.subheader("Petunjuk Singkat")

st.markdown("""
1. Klik menu **Prediksi Kopi** di sidebar.
2. Isi parameter (jenis kopi, jenis kelamin, umur, jam).
3. Klik tombol **Prediksi Penjualan**.
4. Jika diaktifkan, grafik akan menampilkan prediksi untuk semua jam (0–23).
""")

st.info("Silakan pilih halaman di sidebar sebelah kiri untuk mulai.")