# -*- coding: utf-8 -*-
"""1_prediksi_kopi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Soo-H7jI08Hi5qFW5xVmuFE10aIs1kD9
"""



import streamlit as st
import joblib
import pandas as pd
import base64

# ===========================
# CSS Card / Box Transparan
# ===========================
card_style = """
<style>
.card {
    background-color: rgba(255, 255, 255, 0.60);  /* putih 60% transparan */
    padding: 25px;
    border-radius: 12px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.2);
    margin-bottom: 20px;
}
</style>
"""

st.markdown(card_style, unsafe_allow_html=True)

# ===========================
# Fitur Background Image
# ===========================
def add_bg_from_local(bg_kopi):
    with open(bg_kopi, "rb") as f:
        encoded_string = base64.b64encode(f.read()).decode()

    st.markdown(
        f"""
        <style>
        .stApp {{
            background-image: url("data:image/jpg;base64,{encoded_string}");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }}
        </style>
        """,
        unsafe_allow_html=True
    )

# Panggil sebelum UI
add_bg_from_local("bg.jpg")


# ===========================
# Load model
# ===========================
@st.cache_resource
def load_model():
    return joblib.load("model_kopi.pkl")

model = load_model()

# ===========================
# UI
# ===========================
st.title("☕ Prediksi Penjualan Kopi")
st.write("Masukkan informasi pemesan untuk melihat prediksi penjualan.")

# ===========================
# 2. Judul & Deskripsi
# ===========================
st.title("☕ Prediksi Penjualan Kopi")
st.write(
    """
Aplikasi ini memprediksi **jumlah cup kopi** yang akan terjual berdasarkan:
- Jenis kopi
- Jenis kelamin pemesan
- Umur
- Jam pemesanan

Model ini dilatih dari data riwayat penjualan.
"""
)

# ===========================
# 3. Input dari user
# ===========================
st.markdown('<div class="card">', unsafe_allow_html=True)

st.subheader(" Input Prediksi")

col1, col2 = st.columns(2)

jenis_kopi_list = ["Americano", "Latte", "Cappuccino", "Mocha", "Espresso"]

with col1:
    jenis_kopi = st.selectbox(
        "Pilih jenis kopi utama",
        jenis_kopi_list
    )

    bandingkan = st.checkbox("Bandingkan dengan jenis kopi lain?")
    jenis_kopi_2 = None
    if bandingkan:
        jenis_kopi_2 = st.selectbox(
            "Pilih jenis kopi pembanding",
            [jk for jk in jenis_kopi_list if jk != jenis_kopi]
        )

    jenis_kelamin = st.selectbox(
        "Jenis kelamin pemesan",
        ["Laki-laki", "Perempuan"]
    )

with col2:
    umur = st.number_input(
        "Umur pemesan (tahun)",
        min_value=10,
        max_value=80,
        value=25,
        step=1
    )

    jam = st.number_input(
        "Jam pemesanan (0–23)",
        min_value=0,
        max_value=23,
        value=9,
        step=1
    )

show_graph = st.checkbox("Tampilkan grafik prediksi per jam", value=True)

st.markdown("</div>", unsafe_allow_html=True)
# ===========================
# 4. Tombol Prediksi
# ===========================

if st.button(" Prediksi Penjualan"):
    # =======================
    # 1. Prediksi kopi utama di jam yang dipilih
    # =======================
    data_baru = pd.DataFrame([{
        "jenis_kopi": jenis_kopi,
        "jenis_kelamin": jenis_kelamin,
        "umur": umur,
        "jam": jam
    }])

    prediksi = model.predict(data_baru)[0]
    prediksi = round(prediksi, 2)

    st.success(
        f"Perkiraan jumlah cup **{jenis_kopi}** yang akan terjual pada jam {jam}: "
        f"**{prediksi} cup**"
    )

    with st.expander("Lihat detail input yang digunakan"):
        st.write(data_baru)

    # =======================
    # 2. Kalau bandingkan diaktifkan → prediksi kopi kedua
    # =======================
    if bandingkan and jenis_kopi_2 is not None:
        data_baru_2 = pd.DataFrame([{
            "jenis_kopi": jenis_kopi_2,
            "jenis_kelamin": jenis_kelamin,
            "umur": umur,
            "jam": jam
        }])

        prediksi_2 = model.predict(data_baru_2)[0]
        prediksi_2 = round(prediksi_2, 2)

        st.info(
            f"Perkiraan jumlah cup **{jenis_kopi_2}** pada jam {jam}: "
            f"**{prediksi_2} cup**"
        )

    # =======================
    # 3. Grafik prediksi per jam (0–23)
    # =======================
    if show_graph:
        st.markdown("---")
        st.subheader(" Prediksi Penjualan per Jam (0–23)")

        jam_list = list(range(24))

        # --- kopi utama ---
        df_sim_1 = pd.DataFrame([
            {
                "jenis_kopi": jenis_kopi,
                "jenis_kelamin": jenis_kelamin,
                "umur": umur,
                "jam": j
            }
            for j in jam_list
        ])
        pred_1 = model.predict(df_sim_1)

        # DataFrame untuk grafik
        df_grafik = pd.DataFrame({
            "Jam": jam_list,
            jenis_kopi: pred_1
        })

        # --- kopi kedua (kalau ada perbandingan) ---
        if bandingkan and jenis_kopi_2 is not None:
            df_sim_2 = pd.DataFrame([
                {
                    "jenis_kopi": jenis_kopi_2,
                    "jenis_kelamin": jenis_kelamin,
                    "umur": umur,
                    "jam": j
                }
                for j in jam_list
            ])
            pred_2 = model.predict(df_sim_2)
            df_grafik[jenis_kopi_2] = pred_2

        # bulatkan biar enak dibaca
        for col in df_grafik.columns:
            if col != "Jam":
                df_grafik[col] = df_grafik[col].round(2)

        # pakai Jam sebagai index, sehingga tiap kolom = jenis kopi
        st.line_chart(df_grafik.set_index("Jam"))

        # tabel kecil di bawah grafik (opsional)
        with st.expander("Lihat data angka untuk grafik"):
            st.dataframe(df_grafik)
    else:
        st.caption("Grafik dimatikan. Centang opsi **Tampilkan grafik prediksi per jam** untuk melihat grafik.")
else:
    st.info("Silakan isi parameter di atas lalu klik tombol **Prediksi Penjualan**.")