# -*- coding: utf-8 -*-
"""2_eksplorasi_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTucTU7r11-WA4RMHoj7FlZ4boEOx6P_
"""

import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="Eksplorasi Data Kopi",
    page_icon="📊",
    layout="wide"
)

st.title("📊 Eksplorasi Data Penjualan Kopi")
st.write(
    """
Halaman ini digunakan untuk melihat dan memahami pola dari data penjualan kopi
yang digunakan untuk melatih model prediksi.
"""
)

# ===========================
# Fungsi load data
# ===========================
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("data_kopi.csv")
        return df
    except FileNotFoundError:
        return None

df = load_data()

if df is None:
    st.error("File `data_kopi.csv` tidak ditemukan. Pastikan file ada di folder utama project.")
    st.stop()

# ===========================
# Cek kolom
# ===========================
expected_cols = ["jenis_kopi", "jenis_kelamin", "umur", "jam", "jumlah_cup"]
missing = [c for c in expected_cols if c not in df.columns]
if missing:
    st.error(f"Kolom berikut tidak ada di data: {missing}")
    st.write("Kolom yang ada:", list(df.columns))
    st.stop()

# ===========================
# Sidebar Filter
# ===========================
st.sidebar.header("Filter Data")

jenis_kopi_opts = sorted(df["jenis_kopi"].unique())
jenis_kelamin_opts = sorted(df["jenis_kelamin"].unique())

filter_jenis_kopi = st.sidebar.multiselect(
    "Filter jenis kopi",
    options=jenis_kopi_opts,
    default=jenis_kopi_opts
)

filter_jenis_kelamin = st.sidebar.multiselect(
    "Filter jenis kelamin",
    options=jenis_kelamin_opts,
    default=jenis_kelamin_opts
)

min_jam = int(df["jam"].min())
max_jam = int(df["jam"].max())

filter_jam = st.sidebar.slider(
    "Rentang jam",
    min_value=min_jam,
    max_value=max_jam,
    value=(min_jam, max_jam),
    step=1
)

# Terapkan filter
df_filtered = df[
    df["jenis_kopi"].isin(filter_jenis_kopi)
    & df["jenis_kelamin"].isin(filter_jenis_kelamin)
    & df["jam"].between(filter_jam[0], filter_jam[1])
]

st.sidebar.markdown("---")
st.sidebar.write(f"Jumlah baris setelah filter: **{len(df_filtered)}**")

# ===========================
# Tabel data
# ===========================
st.subheader("📄 Data Mentah (Setelah Filter)")

with st.expander("Tampilkan / sembunyikan data"):
    st.dataframe(df_filtered.reset_index(drop=True))

# ===========================
# Statistik dasar
# ===========================
st.subheader("📈 Statistik Dasar")

col_a, col_b, col_c = st.columns(3)

with col_a:
    st.metric("Jumlah baris data", len(df_filtered))

with col_b:
    st.metric("Rata-rata jumlah cup", round(df_filtered["jumlah_cup"].mean(), 2))

with col_c:
    st.metric("Rata-rata umur", round(df_filtered["umur"].mean(), 2))

st.markdown("---")

# ===========================
# Grafik 1: Distribusi jenis kopi
# ===========================
st.subheader("1️⃣ Distribusi Penjualan per Jenis Kopi")

kopi_counts = (
    df_filtered
    .groupby("jenis_kopi")["jumlah_cup"]
    .sum()
    .sort_values(ascending=False)
)

st.bar_chart(kopi_counts)

# ===========================
# Grafik 2: Rata-rata jumlah cup per jam
# ===========================
st.subheader("2️⃣ Rata-rata Jumlah Cup per Jam")

jam_mean = (
    df_filtered
    .groupby("jam")["jumlah_cup"]
    .mean()
    .reset_index()
    .sort_values("jam")
)

st.line_chart(jam_mean.set_index("jam"))

# ===========================
# Grafik 3: Rata-rata per jenis kelamin & jenis kopi
# ===========================
st.subheader("3️⃣ Rata-rata Penjualan per Jenis Kopi dan Jenis Kelamin")

pivot_gender = (
    df_filtered
    .groupby(["jenis_kopi", "jenis_kelamin"])["jumlah_cup"]
    .mean()
    .reset_index()
)

pivot_table = pivot_gender.pivot_table(
    index="jenis_kopi",
    columns="jenis_kelamin",
    values="jumlah_cup"
)

st.bar_chart(pivot_table)

with st.expander("Lihat data agregasi (pivot)"):
    st.dataframe(pivot_table.round(2))